import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/header";
import MainSection from "@/components/mainSection/mainSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>سرپ انجین</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.webp" />
      </Head>
      <div className="container">
          <Header/>
          <MainSection/>
          <div className={styles.arrow}>
              <img src={"/arrow.svg"} alt="arrow for pointer"/>
          </div>
      </div>

    </>
  );
}
